#namespace config map
---
apiVersion: v1
kind: Namespace
metadata:
  name: vscodens
  labels: 
    app: vscode  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vscode-cm
  namespace: vscodens
  labels: 
    app: vscode
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: code-146.190.201.32.nip.io
---
apiVersion: v1
kind: Secret
metadata:
  name: vscode-secret
  namespace: vscodens
  labels: 
    app: vscode
data:
  PASSWORD: c2VuZGhlbHA=
  #PASSWORD: c2VuZGhlbHA= cGFzc3dvcmQ=
  SUDO_PASSWORD: c2VuZGhlbHA=
  