---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vscode-pvc
  namespace: vscodens
spec:
  storageClassName: do-block-storage
  accessModes: #look for a volume that supports both characteristics
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi #minimum for digital ocean 