---
apiVersion: v1 
kind: Secret 
metadata:
  name: ingress-secret 
  namespace: web 
data:
  # my secret key
  API-KEY: bXkgc2VjcmV0IGtleQ==

---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: ingress-cm 
  namespace: web 
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
      <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Document</title>
      </head>
      <body>

          <h1><code>hello, world AHHH</code></h1>
          
      </body>
    </html>