---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
  labels:
    app: bgg
spec:
  type: ClusterIP
  selector:
    app: bgg
    role: db
  ports:
  - name: db
    port: 3306       # Service port
    targetPort: 3306 # Container port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bggns
  labels:
    app: bgg
    role: db
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: bgg
      role: db
  template:
    metadata:
      name: bggdb-pod
      namespace: bggns
      labels:
        app: bgg
        role: db
    spec: 
      containers:
      - name: bggdb
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306


