---
apiVersion: v1
kind: Namespace
metadata:
  name: minions
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-cm
  namespace: minions
  labels: 
    app: minio
data:
  MINIO_ROOT_USER: admin
  # MINIO_ROOT_PASSWORD: miniosecret
  MINIO_DATA_DIR: /data
  MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
  MINIO_DISTRIBUTED_NODES: minio-sts-{0...3}.minio-hsvc.minions.svc.cluster.local
  MINIO_API_PORT_NUMBER: "9000"
  MINIO_CONSOLE_PORT_NUMBER: "9090"